NXP-17742: MongoDB directories
nuxeo/nuxeo-mongodb-ext pull request #1
Opened 2017-01-27 14:06 UTC by funshodavid

New MongoDB implementation of directories. This first version does not include references between directories.

2017-01-27 16:23 UTC, efge requested changes

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-audit/src/main/resources/META-INF/MANIFEST.MF
> +Bundle-SymbolicName: org.nuxeo.ecm.mongodb.ext.audit;singleton:=true
Remove the `Extensions` and `ext` part, they don't bring anything. "MongoDB Audit" is descriptive enough.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-core/src/main/java/org/nuxeo/mongodb/ext/core/MongoDBConnectionHelper.java
> +    public static boolean hasCollection(MongoClient mongoClient, String dbname, String collection) {
Add Javadoc on all public methods.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-core/src/main/java/org/nuxeo/mongodb/ext/core/MongoDBConnectionHelper.java
> +        final MongoIterable<String> collections = mongoClient.getDatabase(dbname).listCollectionNames();
Remove `final`.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-core/src/main/java/org/nuxeo/mongodb/ext/core/MongoDBConnectionHelper.java
> +        }
`import com.google.common.collect.Iterables;` (make sur Guava is in the POM)
`boolean found = Iterables.contains(it, collection);`

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-core/src/main/java/org/nuxeo/mongodb/ext/core/MongoDBSerializationHelper.java
> +
Remove extra blank line. Add Javadoc.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-core/src/main/resources/META-INF/MANIFEST.MF
>  Bundle-SymbolicName: org.nuxeo.ecm.liveconnect.core;singleton:=true
not live connect

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBDirectory.java
> + * MongoDB implementation of a NXDirectory
`NXDirectory` -> `{@link Directory}.`

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBDirectory.java
> +        }
`schema.getFields().forEach(f -> schemaFieldMap.put(f.getName().getLocalName(), f))`

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBDirectory.java
> +        }
I don't like that we do the above check at every call, because it calls `hasCollection` which is costly. It would be better to maintain an `boolean initialized`field to avoid doing it more than once. (SQLDirectory does it indirectly through the `dialect` field.)

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +        props.append(MONGODB_SET, MongoDBSerializationHelper.fieldMapToBson(fieldMap));
I think this creates the document if it doesn't exist yet, which is not what we want. You should add a unit test for that, and probably change the code to add to the update call a query that basically checks `{idField: { "$exists": true }}` and then verify that the update updated exactly one doc.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                throw new DirectoryException("Error while updating the entry");
Add more info about the error in the exception.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                throw new DirectoryException("Error while deleting the entry");
Add more info about the error in the exception.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                    bson.put(entry.getKey(), value);
Factor out the `bson.put(entry.getKey(), v)` part.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                    switch (substringMatchType) {
Note that `// TODO this should be case-insensitive` and add an `@Ignore` unit test that fails to show that we need to implement it.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                MongoClientOptions.builder().serverSelectionTimeout(1000).build());
It looks like some of this should be factored out in MongoDBConnectionHelper.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +            mongoClient.close();
Use try-with-resource as `MongoClient` is `AutoCloseable`.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +                MongoDBSerializationHelper.fieldMapToBson(Collections.singletonMap(getIdField(), id))) > 0;
You can probably had a protected helper method for `MongoDBSerializationHelper.fieldMapToBson(Collections.singletonMap(getIdField(), id)))` as it's used several times.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-directory/src/main/java/org/nuxeo/directory/MongoDBSession.java
> +        } catch (PropertyException e) {
As this is a new directory type let's remove this crappy exception swallowing and just let the `PropertyException` be raised to the caller.

2017-01-27 16:23 UTC, efge commented on nuxeo-mongodb-test/src/test/java/TestMongoDBDirectory.java
> +        }
Please add tests about `query`.

2017-01-30 13:54 UTC, kevinleturc commented
👍

2017-01-30 15:00 UTC, merged